apiVersion: v1
kind: Namespace
metadata:
  name: httpd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: httpd
data:
  index.html: |
    <html>
    <h1>Welcome to HTTPD Deployment</h1>
    </br>
    <h1>Hi! i was just detected by the boundary scanner :)</h1>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-nautilus
  namespace: httpd
  labels:
    app: httpd_app_nautilus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd_app_nautilus
  template:
    metadata:
      labels:
        app: httpd_app_nautilus
    spec:
      volumes :
      - name: httpd-index-file
        configMap :
         name: index-html-configmap
      containers:
      - name: httpd-container-nautilus
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts :
        - name: httpd-index-file
          mountPath: /usr/local/apache2/htdocs/
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: httpd
spec:
  selector:
    app: httpd_app_nautilus
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP