replicaCount: 1

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: alb
  hostname: "*.com"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip